# Numpy: Numeric computing library

NumPy is one of the most important libraries in Python for data processing. It is a numeric computing library. In Python, numeric processing is slow, but when you go down to deep and work with large datasets, Python itself is not right for that. In here, Numpy is solving that. 

#### Note: We may not be working with Numpy in real life situations directly. However, other libraries demand Numpy for numeric processing before them

In [2]:
import sys    # interact with the Python interpreter and access command-line arguments
import numpy as np

## Basic Numpy Arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [12]:
a = np.array([1,2,3,4]) # creating 1st array

In [13]:
b = np.array([0, .5, 1.5, 2]) # creating 2nd array

In [14]:
a[0], a[1] # geting 1st and 2nd element of array

(1, 2)

In [15]:
a[0:] # slicing from 1st element to the end

array([1, 2, 3, 4])

In [16]:
a[1:3] # slicing from 2nd element to the 3rd (3rd not included)

array([2, 3])

In [17]:
a[1:-1] # slicing from 2nd element to last element

array([2, 3])

In [21]:
a[::2] # extended slicing every 2nd element from array

array([1, 3])

In [22]:
b

array([0. , 0.5, 1.5, 2. ])

In [10]:
b[0], b[2], b[-1] # multi indexing

(0.0, 1.5, 2.0)

In [23]:
b[[0, 2, -1]] # creating another array using multi indexing that works in arrays not lists

array([0. , 1.5, 2. ])

## Array Types

In [24]:
a

array([1, 2, 3, 4])

In [26]:
a.dtype # type of array

dtype('int32')

In [27]:
b

array([0. , 0.5, 1.5, 2. ])

In [28]:
b.dtype

dtype('float64')

In [32]:
np.array([1, 2, 3, 4], dtype=np.float32) # changing type of array

array([1., 2., 3., 4.], dtype=float32)

In [36]:
c = np.array(['a', 'b', 'c']) # string type

In [37]:
c.dtype

dtype('<U1')

In [38]:
d = np.array([{'a':1}, sys])

In [40]:
d.dtype # nupmy doesn't store this type of compound data

dtype('O')

## Dimensions and shapes

In [41]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [43]:
A.shape # our matrix is 2x3 matrix

(2, 3)

In [45]:
A.ndim # dimensions of matrix, 1 vertical and 1 horizontal

2

In [47]:
A.size # total numbers of elements we have

6

In [50]:
# creating 3 dimensinal array - cube
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [51]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [52]:
B.shape

(2, 2, 3)

In [53]:
B.ndim

3

In [54]:
B.size

12

## Indexing and Slicing Matrices

In [68]:
# Creating a square matrix
A = np.array([
#   0. 1. 2
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9] #2
])

In [59]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
A[1] # 2nd element of matrix

array([4, 5, 6])

In [67]:
A[1][0] # 1st element of 2nd row in matrix

4

In [62]:
A[1,0]

4

In [69]:
A[0:2] # selecting from row1 to row2

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
A[:, :2] # select every row, select every element up t0 column 2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [70]:
A[:2, :2] # select rows upto row 2, select every element upto column 2

array([[1, 2],
       [4, 5]])

In [71]:
A[:2, 2:]

array([[3],
       [6]])

In [72]:
A[1] = np.array([10,10,10]) # modifying row in array

In [73]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [74]:
A[2] = 99

In [75]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary Statistics

In [76]:
 a = np.array([1, 2, 3, 4])

In [77]:
a.sum() # sum of elements

10

In [78]:
a.mean() # mean of array

2.5

In [79]:
a.std() # standard deviation of an array
# The standard deviation provides a single number to describe the spread of values in a dataset. 
# A higher standard deviation indicates greater variability in the data, 
# while a lower standard deviation indicates that the data points tend to be closer to the mean.

1.118033988749895

In [82]:
a.var() # variance of an array
# It is the average of the squared differences from the mean

1.25

In [83]:
A  = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [84]:
A.sum()

45

In [85]:
A.mean()

5.0

In [86]:
A.std()

2.581988897471611

In [87]:
A.var()

6.666666666666667

In [88]:
A.sum(axis = 0) # sum of axis y

array([12, 15, 18])

In [89]:
A.sum(axis = 1) # sum of axis x

array([ 6, 15, 24])

In [91]:
A.mean(axis = 0)

array([4., 5., 6.])

## Broadcasting and Vectorized operations
This is one of fundamental topics and reated to booleans

In [109]:
a = np.arange(4)

In [110]:
a

array([0, 1, 2, 3])

In [111]:
a + 10

array([10, 11, 12, 13])

In [112]:
a * 10

array([ 0, 10, 20, 30])

In [113]:
a

array([0, 1, 2, 3])

In [114]:
a+=10 # willmodify the array

In [115]:
a

array([10, 11, 12, 13])

In [116]:
l = [0,1,2,3]

In [117]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [118]:
a = np.arange(4)

In [119]:
a

array([0, 1, 2, 3])

In [120]:
b = np.array([10,10,10,10])

In [121]:
b

array([10, 10, 10, 10])

In [123]:
a + b

array([10, 11, 12, 13])

In [124]:
a*b

array([ 0, 10, 20, 30])

## Boolean arrays
*(Also called masks)*

In [125]:
a = np.arange(4)

In [126]:
a

array([0, 1, 2, 3])

In [127]:
a[[0, -1]]

array([0, 3])

In [128]:
a[[True, False, False, True]]

array([0, 3])

In [130]:
a >= 2

array([False, False,  True,  True])

In [131]:
a[a >= 2]

array([2, 3])

In [132]:
a.mean()

1.5

In [134]:
a[a > a.mean()]

array([2, 3])

In [133]:
a[~(a > a.mean())] 

array([0, 1])

In [ ]:
~ # NOT operator
& # AND operator
| # OR operator

In [139]:
A = np.random.randint(100, size = (3,3))

In [140]:
A

array([[44, 25, 42],
       [84, 76, 74],
       [29, 19, 79]])

In [141]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([44, 42, 76, 29, 79])

In [142]:
A > 30

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [144]:
A[A>30]

array([44, 42, 84, 76, 74, 79])

## Linear Algebra

In [145]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [146]:
B = np.array([
    [6,5],
    [4,4],
    [2,1]
])

In [148]:
A.dot(B) # multiplication, dot product

array([[20, 16],
       [56, 46],
       [92, 76]])

In [154]:
A @ B # multiplication or dot product

array([[20, 16],
       [56, 46],
       [92, 76]])

In [155]:
B.T # transpose of a matrix

array([[6, 4, 2],
       [5, 4, 1]])

In [156]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
B.T @ A

array([[36, 48, 60],
       [28, 38, 48]])

## Size of objects in Memory

### Int, floats

In [160]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [161]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [162]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [166]:
np.dtype(np.int8).itemsize

1

### Lists are even larger

In [167]:
# A one-element list
sys.getsizeof([1])

64

In [168]:
# An array of one element in numpy
np.array([1]).nbytes

4

## Useful Numpy functions

### `random`

In [4]:
np.random.random(size=2)

array([0.73738244, 0.64998168])

In [179]:
np.random.normal(size=2)

array([-0.30710429,  1.3898143 ])

In [181]:
np.random.rand(2, 4)

array([[0.10381337, 0.43638261, 0.98795217, 0.57495775],
       [0.64928476, 0.58437611, 0.2846259 , 0.59431433]])

### `arange`

In [182]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [184]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### `reshape`

In [185]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [186]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### `linspace`

In [188]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [189]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [9]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### `zeros`, `ones`, `empty`

In [191]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [192]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [194]:
np.zeros((3,3), dtype = np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [195]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [196]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [197]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [198]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### `identity`, `eye`

In [199]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [200]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [202]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [204]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [205]:
"Hello world"[6]

'w'